# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
