# Generated by Django 2.1.3 on 2018-12-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20170320_0255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='item',
            name='list',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
