# Generated by Django 2.1.4 on 2018-12-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0017_list_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
